# Generated by Django 5.1 on 2024-08-29 09:32

import api.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField()),
                ('industry', models.CharField(max_length=100)),
                ('founded_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)])),
                ('website', models.URLField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'indexes': [models.Index(fields=['name'], name='api_company_name_35e8e7_idx'), models.Index(fields=['slug'], name='api_company_slug_ecba8e_idx'), models.Index(fields=['industry'], name='api_company_industr_47505d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TourStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('page_name', models.CharField(max_length=100)),
                ('section_id', models.CharField(blank=True, max_length=100, null=True)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('blog', 'Blog'), ('interactive', 'Interactive')], default='blog', max_length=20)),
                ('content', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(default=api.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, related_name='tour_steps', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, default=api.models.get_default_company, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.company')),
                ('tour_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tourstep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Histories',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_content_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('text', 'Text'), ('interactive', 'Interactive')], default='text', max_length=20)),
                ('interests', models.JSONField(default=list)),
                ('points', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.company')),
                ('current_tour_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tourstep')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='api.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'key'], name='api_company_company_953d73_idx'), models.Index(fields=['is_public'], name='api_company_is_publ_e57c8f_idx')],
                'unique_together': {('company', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('text', 'Text'), ('interactive', 'Interactive')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='api.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'content_type'], name='api_content_company_2c340a_idx'), models.Index(fields=['is_active'], name='api_content_is_acti_9a24a8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tourstep',
            index=models.Index(fields=['company', 'order'], name='api_tourste_company_d4a7da_idx'),
        ),
        migrations.AddIndex(
            model_name='tourstep',
            index=models.Index(fields=['content_type'], name='api_tourste_content_b370b2_idx'),
        ),
        migrations.AddIndex(
            model_name='tourstep',
            index=models.Index(fields=['is_active'], name='api_tourste_is_acti_79262a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tourstep',
            unique_together={('company', 'order')},
        ),
        migrations.AddIndex(
            model_name='userhistory',
            index=models.Index(fields=['user', 'company'], name='api_userhis_user_id_a76b82_idx'),
        ),
        migrations.AddIndex(
            model_name='userhistory',
            index=models.Index(fields=['timestamp'], name='api_userhis_timesta_8fcd7c_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user', 'company'], name='api_userpro_user_id_7b803e_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['preferred_content_type'], name='api_userpro_preferr_229fc4_idx'),
        ),
    ]
