# Generated by Django 5.1 on 2024-08-30 06:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourstep',
            options={'ordering': ['order']},
        ),
        migrations.RemoveIndex(
            model_name='tourstep',
            name='api_tourste_company_d4a7da_idx',
        ),
        migrations.RemoveIndex(
            model_name='tourstep',
            name='api_tourste_content_b370b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='tourstep',
            name='api_tourste_is_acti_79262a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='tourstep',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tourstep',
            name='next_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_step', to='api.tourstep'),
        ),
        migrations.AlterField(
            model_name='company',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
