# Generated by Django 3.2.12 on 2024-08-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourstep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_images'),
        ),
        migrations.AddField(
            model_name='tourstep',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='tour_videos'),
        ),
    ]
