# Generated by Django 3.2.12 on 2024-08-26 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240825_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=200)),
                ('tour_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='api.tourstep')),
            ],
        ),
    ]
