# Generated by Django 3.2.25 on 2024-08-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20240826_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourstep',
            name='blog_content',
        ),
        migrations.RemoveField(
            model_name='tourstep',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tourstep',
            name='video',
        ),
        migrations.AddField(
            model_name='tourstep',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tourstep',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('blog', 'Blog')], default='blog', max_length=5),
        ),
    ]
